import "./bootstrap.js";
import "./scrollRpage2and4.js";
import "./navBurger.js";
import "./sladerPortfolio.js";
import "./color.js";
import "./showMore.js";
import "./faq.js";
import "./formContact.js";
import "./phoneMask.js";
